---
abstract: 'boxer command line utils'
author:
  - 'Jonas Smedegaard (JONASS) <jonass@cpan.org>'
build_requires:
  English: '0'
  File::Spec: '0'
  Test::Compile: '0'
  Test::Fixme: '0'
  Test::MinimumVersion: '0'
  Test::More: '0.61'
  Test::Pod: '1.00'
  Test::Synopsis: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.023, CPAN::Meta::Converter version 2.142690'
keywords:
  - Debian
  - Distribution
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Boxer
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Boxer:
    file: lib/Boxer.pm
    version: '0.001'
  Boxer::CLI:
    file: lib/Boxer/CLI.pm
    version: '0.001'
  Boxer::CLI::Command:
    file: lib/Boxer/CLI/Command.pm
    version: '0.001'
  Boxer::CLI::Command::About:
    file: lib/Boxer/CLI/Command/About.pm
    version: '0.001'
  Boxer::CLI::Command::Aliases:
    file: lib/Boxer/CLI/Command/Aliases.pm
    version: '0.001'
  Boxer::CLI::Command::Commands:
    file: lib/Boxer/CLI/Command/Commands.pm
    version: '0.001'
  Boxer::CLI::Command::Compose:
    file: lib/Boxer/CLI/Command/Compose.pm
    version: '0.001'
  Boxer::Role::Interact:
    file: lib/Boxer/Role/Interact.pm
    version: '0.001'
  Boxer::Task:
    file: lib/Boxer/Task.pm
    version: '0.001'
  Boxer::Task::Classify:
    file: lib/Boxer/Task/Classify.pm
    version: '0.001'
  Boxer::Task::Serialize:
    file: lib/Boxer/Task/Serialize.pm
    version: '0.001'
requires:
  App::Cmd: '0'
  Capture::Tiny: '0'
  File::HomeDir: '0'
  JSON: '2.00'
  Module::Runtime: '0'
  Moo: '1.000000'
  MooX::Types::MooseLike::Base: '0'
  Path::Class: '0'
  Path::Tiny: '0'
  Role::Commons: '0'
  Try::Tiny: '0'
  Types::Path::Tiny: '0'
  Types::Standard: '0'
  YAML::XS: '0'
  autodie: '0'
  match::simple: '0'
  namespace::clean: '0'
  strictures: '0'
resources:
  Identifier: http://purl.org/NET/cpan-uri/dist/Boxer/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=App-Boxer
  homepage: https://metacpan.org/release/Boxer
  license: http://dev.perl.org/licenses/
  repository: https://anonscm.debian.org/cgit/boxer/App-Boxer.git
version: '0.001'
x_help_wanted:
  - documenter
  - tester
x_provides_scripts:
  boxer:
    file: bin/boxer
